=== cnhartley/dna-analyzer/dnaa-common/src/main/resources/xml/AminoAcidLibXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Simple type definitions -->
  
  <xs:simpleType name="nameType">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="shortStringType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][a-zA-Z]{2}" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="singleLetterType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]{1}" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="codonType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="flagType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[Ss][Tt]([Oo][Pp]|[Aa][Rr][Tt])" />
    </xs:restriction>
  </xs:simpleType>
  
  <!-- Complex type definitions -->
  
  <xs:complexType name="aminoAcidType">
    <xs:sequence>
      <xs:element name="name" type="nameType" />
      <xs:element name="short" type="shortStringType" />
      <xs:element name="symbol" type="singleLetterType" />
      <xs:element name="flag" type="flagType" minOccurs="0"/>
      <xs:element name="codon" type="codonType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="aminoAcidsType">
    <xs:sequence>
      <xs:element name="aminoacid" type="aminoAcidType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  
  <!-- The root type for the library -->
  
  <xs:element name="aminoacids" type="aminoAcidsType" />
  
</xs:schema>

=== cnhartley/dna-analyzer/dnaa-webapp/src/main/webapp/xml/aminoacids.xml
<?xml version="1.0" encoding="UTF-8"?>
<aminoacids xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="AminoAcidLibXMLSchema.xsd">
<!-- last update on September 16, 2014 -->

<aminoacid>
   <name>Arginine</name>
   <short>Arg</short>
   <symbol>R</symbol>

   <codon>AGA</codon><!-- 001000 = 0x08 -->
   <codon>AGG</codon><!-- 001010 = 0x0A -->
   <codon>CGA</codon><!-- 011000 = 0x18 -->
   <codon>CGC</codon><!-- 011001 = 0x19 -->
   <codon>CGG</codon><!-- 011010 = 0x1A -->
   <codon>CGU</codon><!-- 011011 = 0x1B -->
</aminoacid>

<aminoacid>
   <name>Serine</name>
   <short>Ser</short>
   <symbol>S</symbol>

   <codon>AGC</codon><!-- 001001 = 0x09 -->
   <codon>AGU</codon><!-- 001011 = 0x0B -->
   <codon>UCA</codon><!-- 110100 = 0x34 -->
   <codon>UCC</codon><!-- 110101 = 0x35 -->
   <codon>UCG</codon><!-- 110110 = 0x36 -->
   <codon>UCU</codon><!-- 110111 = 0x37 -->
</aminoacid>

<aminoacid>
   <name>Lysine</name>
   <short>Lys</short>
   <symbol>K</symbol>

   <codon>AAA</codon><!-- 000000 = 0x00 -->
   <codon>AAG</codon><!-- 000010 = 0x02 -->
</aminoacid>

<aminoacid>
   <name>Asparagine</name>
   <short>Asn</short>
   <symbol>N</symbol>

   <codon>AAC</codon><!-- 000001 = 0x01 -->
   <codon>AAU</codon><!-- 000011 = 0x03 -->
</aminoacid>

<aminoacid>
   <name>Threonine</name>
   <short>Thr</short>
   <symbol>T</symbol>

   <codon>ACA</codon><!-- 000100 = 0x04 -->
   <codon>ACC</codon><!-- 000101 = 0x05 -->
   <codon>ACG</codon><!-- 000110 = 0x06 -->
   <codon>ACU</codon><!-- 000111 = 0x07 -->
</aminoacid>

<!-- Start codon -->
<aminoacid>
   <name>Methionine</name>
   <short>Met</short>
   <symbol>M</symbol>
   
   <flag>start</flag>
   
   <codon>AUG</codon><!-- 001110 = 0x0E -->
</aminoacid>

<aminoacid>
   <name>Isoleucine</name>
   <short>Ile</short>
   <symbol>I</symbol>

   <codon>AUA</codon><!-- 001100 = 0x0C -->
   <codon>AUC</codon><!-- 001101 = 0x0D -->
   <codon>AUU</codon><!-- 001111 = 0x0F -->
</aminoacid>

<aminoacid>
   <name>Glutamine</name>
   <short>Gln</short>
   <symbol>Q</symbol>

   <codon>CAA</codon><!-- 010000 = 0x10 -->
   <codon>CAG</codon><!-- 010010 = 0x12 -->
</aminoacid>

<aminoacid>
   <name>Histidine</name>
   <short>His</short>
   <symbol>H</symbol>

   <codon>CAC</codon><!-- 010001 = 0x11 -->
   <codon>CAU</codon><!-- 010011 = 0x13 -->
</aminoacid>

<aminoacid>
   <name>Proline</name>
   <short>Pro</short>
   <symbol>P</symbol>

   <codon>CCA</codon><!-- 010100 = 0x14 -->
   <codon>CCC</codon><!-- 010101 = 0x15 -->
   <codon>CCG</codon><!-- 010110 = 0x16 -->
   <codon>CCU</codon><!-- 010111 = 0x17 -->
</aminoacid>

<aminoacid>
   <name>Leucine</name>
   <short>Leu</short>
   <symbol>L</symbol>

   <codon>CUA</codon><!-- 011100 = 0x1C -->
   <codon>CUC</codon><!-- 011101 = 0x1D -->
   <codon>CUG</codon><!-- 011110 = 0x1E -->
   <codon>CUU</codon><!-- 011111 = 0x1F -->
   <codon>UUA</codon><!-- 111100 = 0x3C -->
   <codon>UUG</codon><!-- 111110 = 0x3E -->
</aminoacid>

<aminoacid>
   <name>Tryptophan</name>
   <short>Trp</short>
   <symbol>W</symbol>

   <codon>UGG</codon><!-- 111010 = 0x3A -->
</aminoacid>

<!-- Stop codon -->
<!-- #TODO need to modify this for each actual stop amino acid. -->
<aminoacid>
   <name>stop</name>
   <short>Stp</short>
   <symbol>X</symbol>
   
   <flag>stop</flag>

   <codon>UAA</codon><!-- 110000 = 0x30 -->
   <codon>UAG</codon><!-- 110010 = 0x32 -->
   <codon>UGA</codon><!-- 111000 = 0x38 -->
</aminoacid>

<aminoacid>
   <name>Cysteine</name>
   <short>Cys</short>
   <symbol>C</symbol>

   <codon>UGC</codon><!-- 111001 = 0x39 -->
   <codon>UGU</codon><!-- 111011 = 0x3B -->
</aminoacid>

<aminoacid>
   <name>Tyrosine</name>
   <short>Tyr</short>
   <symbol>Y</symbol>

   <codon>UAC</codon><!-- 110001 = 0x31 -->
   <codon>UAU</codon><!-- 110011 = 0x33 -->
</aminoacid>

<aminoacid>
   <name>Phenylalanine</name>
   <short>Phe</short>
   <symbol>F</symbol>

   <codon>UUC</codon><!-- 111101 = 0x3D -->
   <codon>UUU</codon><!-- 111111 = 0x3F -->
</aminoacid>

<aminoacid>
   <name>Glycine</name>
   <short>Gly</short>
   <symbol>G</symbol>

   <codon>GGA</codon><!-- 101000 = 0x28 -->
   <codon>GGC</codon><!-- 101001 = 0x29 -->
   <codon>GGG</codon><!-- 101010 = 0x2A -->
   <codon>GGU</codon><!-- 101011 = 0x2B -->
</aminoacid>

<aminoacid>
   <name>Glutamic acid</name>
   <short>Glu</short>
   <symbol>E</symbol>

   <codon>GAA</codon><!-- 100000 = 0x20 -->
   <codon>GAG</codon><!-- 100010 = 0x22 -->
</aminoacid>

<aminoacid>
   <name>Aspartic acid</name>
   <short>Asp</short>
   <symbol>D</symbol>

   <codon>GAC</codon><!-- 100001 = 0x21 -->
   <codon>GAU</codon><!-- 100011 = 0x23 -->
</aminoacid>

<aminoacid>
   <name>Alanine</name>
   <short>Ala</short>
   <symbol>A</symbol>

   <codon>GCA</codon><!-- 100100 = 0x24 -->
   <codon>GCC</codon><!-- 100101 = 0x25 -->
   <codon>GCG</codon><!-- 100110 = 0x26 -->
   <codon>GCU</codon><!-- 100111 = 0x27 -->
</aminoacid>

<aminoacid>
   <name>Valine</name>
   <short>Val</short>
   <symbol>V</symbol>

   <codon>GUA</codon><!-- 101100 = 0x2C -->
   <codon>GUC</codon><!-- 101101 = 0x2D -->
   <codon>GUG</codon><!-- 101110 = 0x2E -->
   <codon>GUU</codon><!-- 101111 = 0x2F -->
</aminoacid>

</aminoacids>
